remote_theme: LeNPaul/portfolio-jekyll-theme
plugins:
  - jekyll-remote-theme
title: Portfolio
description: Bookmark this and/or share to a friend or colleague that may need some freelance web development!
